// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl6Ne-hCeLSsZ04S1kWtH_dk5wwEekkOU',
    appId: '1:115250163976:web:62a812356d8ecf1dc3fcbd',
    messagingSenderId: '115250163976',
    projectId: 'easy-super-apps',
    authDomain: 'easy-super-apps.firebaseapp.com',
    storageBucket: 'easy-super-apps.appspot.com',
    measurementId: 'G-NX1E29DG9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKnzsMiJSaqph1Rw9SsZyD_e_lh2XgGXQ',
    appId: '1:115250163976:android:ffa5c825094d47b7c3fcbd',
    messagingSenderId: '115250163976',
    projectId: 'easy-super-apps',
    storageBucket: 'easy-super-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3r5RrUkTUyTj_UsDn56vr_wC4TVoCdrY',
    appId: '1:115250163976:ios:375d7579717e8169c3fcbd',
    messagingSenderId: '115250163976',
    projectId: 'easy-super-apps',
    storageBucket: 'easy-super-apps.appspot.com',
    iosClientId: '115250163976-rdg0qc1arjt1lvgo6bg27pcfta73fmkl.apps.googleusercontent.com',
    iosBundleId: 'com.easysuperapps.driverIntegrated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3r5RrUkTUyTj_UsDn56vr_wC4TVoCdrY',
    appId: '1:115250163976:ios:375d7579717e8169c3fcbd',
    messagingSenderId: '115250163976',
    projectId: 'easy-super-apps',
    storageBucket: 'easy-super-apps.appspot.com',
    iosClientId: '115250163976-rdg0qc1arjt1lvgo6bg27pcfta73fmkl.apps.googleusercontent.com',
    iosBundleId: 'com.easysuperapps.driverIntegrated',
  );
}
